# azure-pipelines.yml
trigger: none

pool:
  name: 'pagopa-dev-loadtest-linux'

parameters:
  - name: "TEST_TYPE"
    displayName: "Test type"
    type: string
    values:
      - "load"
      - "spike"
      - "stress"
      - "soak"
  - name: "SCRIPT"
    displayName: "Script name"
    type: string
    values:
      - full_load_test

variables:
    API_SUBSCRIPTION_KEY: $(DEV_POC_ENROLLMENT_SUB_KEY)

steps:
  - script: |
      cd ./performance-test/src
      docker pull grafana/k6
    displayName: Pull k6 image

  - script: |
      cd ./performance-test
      sh ./run_performance_test.sh dev ${{ parameters.TEST_TYPE }} ${{ parameters.SCRIPT }} pocquarkusk6 $(API_SUBSCRIPTION_KEY)
    displayName: Run k6 ${{ parameters.SCRIPT }} on dev
