version: '3.8'

services:
  app:
    container_name: 'pagopa-poc-quarkus'
    image: ${image}
    env_file:
      - ./config/.env
    ports:
      - "8080:8080"
    networks:
      app_net:

  azure-storage:
    container_name: 'azure-storage-quarkus'
    image: mcr.microsoft.com/azure-storage/azurite@sha256:2628ee10a72833cc344b9d194cd8b245543892b307d16cf26a2cf55a15b816af
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
    networks:
      app_net:
        ipv4_address: 10.30.0.3

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.30.0.0/16
          gateway: 10.30.0.1